// ProgramParams_dark.JS - файл с параметрами запуска программы, тёмная цветовая тема
// Проект Graphite 5.0
// TrollingCont
// 11.02.2017

let programParams = {
	GSMetrics: {
		startX: 0,
		startY: 0,
		width: 1362,
		height: 1362,
		offsetX: 681,
		offsetY: 681,
		scaleX: 32,
		scaleY: 24
	},
	colors: {
		GSBackground: "#202020",
		GSLines: "#7F7F7F",
		GSMainLines: "#F0F0F0",
	},
	startPlugins: true
}